project:
  type: website
  output-dir: docs

website:
  title: "kalyara"
  navbar:
    left:
      - href: index.qmd
        text: início
      - projetos.qmd 
      
      

format:
  html:
    theme: united
    css: styles.css
    toc: true



